In [35]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler , LabelEncoder , OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.base import BaseEstimator, TransformerMixin
from xgboost import XGBClassifier
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

In [2]:
data = pd.read_csv("/home/sheela/Downloads/breast-cancer-dataset.csv")
data.head()

,S/N,Year,Age,Menopause,Tumor Size (cm),Inv-Nodes,Breast,Metastasis,Breast Quadrant,History,Diagnosis Result
0,1,2019,40,1,2,0,Right,0,Upper inner,0,Benign
1,2,2019,39,1,2,0,Left,0,Upper outer,0,Benign
2,3,2019,45,0,4,0,Left,0,Lower outer,0,Benign
3,4,2019,26,1,3,0,Left,0,Lower inner,1,Benign
4,5,2019,21,1,1,0,Right,0,Upper outer,1,Benign

In [18]:
data.isnull().sum()

Age                            0
Breast Quadrant_Lower inner    0
Breast Quadrant_Lower outer    0
Diagnosis Result               0
Breast                         0
dtype: int64

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          5 non-null      int64
 1   Breast Quadrant_Lower inner  5 non-null      int64
 2   Breast Quadrant_Lower outer  5 non-null      int64
 3   Diagnosis Result             5 non-null      int64
 4   Breast                       5 non-null      int64
dtypes: int64(5)
memory usage: 328.0 bytes

In [5]:
data.describe()

              S/N         Age   Menopause
count  213.000000  213.000000  213.000000
mean   107.000000   39.784038    0.666667
std     61.631972   14.096712    0.472515
min      1.000000   13.000000    0.000000
25%     54.000000   30.000000    0.000000
50%    107.000000   40.000000    1.000000
75%    160.000000   49.000000    1.000000
max    213.000000   77.000000    1.000000

In [6]:
# data = pd.get_dummies(data , columns= ["Breast Quadrant"] , drop_first = True)
# data = data.drop(columns=["S/N", "Year", "Breast Quadrant_Upper outer"])

In [7]:
data = data.loc[: , ~data.columns.duplicated()]

In [8]:
data

,S/N,Year,Age,Menopause,Tumor Size (cm),Inv-Nodes,Breast,Metastasis,Breast Quadrant,History,Diagnosis Result
0,1,2019,40,1,2,0,Right,0,Upper inner,0,Benign
1,2,2019,39,1,2,0,Left,0,Upper outer,0,Benign
2,3,2019,45,0,4,0,Left,0,Lower outer,0,Benign
3,4,2019,26,1,3,0,Left,0,Lower inner,1,Benign
4,5,2019,21,1,1,0,Right,0,Upper outer,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...
208,209,2020,49,1,6,3,Right,1,Lower inner,1,Malignant
209,210,2020,28,1,3,0,Left,0,Upper inner,0,Benign
210,211,2020,22,1,1,0,Left,0,Upper outer,1,Benign
211,212,2020,19,1,1,0,Left,0,Lower inner,1,Benign
212,213,2020,50,0,4,0,Right,0,Lower outer,1,Benign

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   S/N               213 non-null    int64
 1   Year              213 non-null    object
 2   Age               213 non-null    int64
 3   Menopause         213 non-null    int64
 4   Tumor Size (cm)   213 non-null    object
 5   Inv-Nodes         213 non-null    object
 6   Breast            213 non-null    object
 7   Metastasis        213 non-null    object
 8   Breast Quadrant   213 non-null    object
 9   History           213 non-null    object
 10  Diagnosis Result  213 non-null    object
dtypes: int64(3), object(8)
memory usage: 18.4+ KB

In [13]:
# # Sample DataFrame
# data = pd.DataFrame({
#     "Age": [40, 39, 45, 26, 21],
#     "Breast Quadrant_Lower inner": [True, False, False, True, False],
#     "Breast Quadrant_Lower outer": [False, False, True, False, False],
#     "Diagnosis Result": ["Benign", "Benign", "Malignant", "Benign", "Benign"],
#     "Breast": ["Right", "Left", "Left", "Right", "Left"]
# })

# # Custom Label Encoder Transformer
# class LabelEncoderTransformer(BaseEstimator, TransformerMixin):
#     def fit(self, X, y=None):
#         self.label_encoder = LabelEncoder()
#         return self

#     def transform(self, X):
#         return X.apply(self.label_encoder.fit_transform)

# # Manually identify categorical columns and numeric columns
# categorical_columns = ["Breast Quadrant_Lower inner", "Breast Quadrant_Lower outer", "Diagnosis Result", "Breast"]
# numeric_columns = ["Age"]  # Specifically include numeric columns

# # # ColumnTransformer applies the transformation only to the categorical columns
# preprocessor = ColumnTransformer(
#     transformers=[('label_encoder', LabelEncoderTransformer(), categorical_columns)],
#     remainder="passthrough"  # Non-categorical columns like 'Age' remain unchanged
# )

# # Pipeline creation
# pipeline = Pipeline(steps=[('preprocessor', preprocessor)])

# # Applying transformations
# data_transformed = pipeline.fit_transform(data)

# # Convert to DataFrame with original column names
# data_transformed = pd.DataFrame(data_transformed, columns=data.columns)

# print(data_transformed)

In [15]:
# Sample DataFrame
data = pd.DataFrame({
    "Age": [40, 39, 45, 26, 21],
    "Breast Quadrant_Lower inner": [True, False, False, True, False],
    "Breast Quadrant_Lower outer": [False, False, True, False, False],
    "Diagnosis Result": ["Benign", "Benign", "Malignant", "Benign", "Benign"],
    "Breast": ["Right", "Left", "Left", "Right", "Left"]
})

# Manually identify categorical columns and numeric columns
categorical_columns = ["Breast Quadrant_Lower inner", "Breast Quadrant_Lower outer", "Diagnosis Result", "Breast"]
numeric_columns = ["Age"]  # Specifically include numeric columns

le = LabelEncoder()
data[categorical_columns] = data[categorical_columns].apply(le.fit_transform)
data

,Age,Breast Quadrant_Lower inner,Breast Quadrant_Lower outer,Diagnosis Result,Breast
0,40,1,0,0,1
1,39,0,0,0,0
2,45,0,1,1,0
3,26,1,0,0,1
4,21,0,0,0,0

In [36]:
x = data[["Age","Breast Quadrant_Lower inner", "Breast Quadrant_Lower outer", "Breast"]]
y = data['Diagnosis Result']

sc = StandardScaler()
x_scaled = sc.fit_transform(x)

x_train, x_test , y_train , y_test = train_test_split(x_scaled, y , test_size = 0.3 , random_state = 42 )

#train multiple model
models = {
    "svm": SVC(kernel = "linear"),
    "Random Forest" : RandomForestClassifier(n_estimators = 100 , random_state = 42),
    "XGboost": XGBClassifier(eval_matric = "logloss"),
    "logistic Regression" : LogisticRegression()
}

# Fit models and evaluate
for name , model in models.items():
    model.fit(x_train , y_train)
    y_pred = model.predict(x_test)
    evaluate = accuracy_score(y_pred , y_test)
    print(f"{name} Evaluate : {evaluate:.4f}")

svm Evaluate : 0.5000
Random Forest Evaluate : 1.0000
XGboost Evaluate : 1.0000
logistic Regression Evaluate : 1.0000

In [53]:
#Compare Predictions for Different Sample Groups
#how age affect cancer?
Age_threshold = data["Age"].median()
age_column_index = data.columns.get_loc("Age")  # Get index of "Age" in DataFrame
age_column = x_test[:, age_column_index]
young_patients = x_test[age_column <= Age_threshold]
old_patients = x_test[age_column > Age_threshold]

if len(young_patients) > 0:
    young_pred = models["Random Forest"].predict(young_patients)
    young_malignant_rate = (young_pred.sum() / len(young_pred)) * 100
    print(f"Malignancy Rate in Young Patients: {young_malignant_rate:.2f}%")
else:
    print("No young patients in the dataset.")

if len(old_patients) > 0:
    old_pred = models["Random Forest"].predict(old_patients)
    old_malignant_rate = (old_pred.sum() / len(old_pred)) * 100
    print(f"Malignancy Rate in Old Patients: {old_malignant_rate:.2f}%")
else:
    print("No old patients in the dataset.")

Malignancy Rate in Young Patients: 0.00%
No old patients in the dataset.